CREATE TABLE ManagerType(
        managerTid INTEGER UNSIGNED auto_increment NOT NULL,
        managertype VARCHAR(50) NOT NULL,
        PRIMARY KEY (managerTid)
)ENGINE=INNODB auto_increment = 80000;

-- INSERT INTO ManagerType VALUES(80001,"TEAM MANAGER");
-- INSERT INTO ManagerType VALUES(80003,"TEAM MANAGER");
-- INSERT INTO ManagerType VALUES(80004,"TEAM MANAGER");
-- INSERT INTO ManagerType VALUES(80005,"TEAM MANAGER");
-- INSERT INTO ManagerType VALUES(80002,"REFEREE MANAGER");
