CREATE TABLE Player(
		playerid INTEGER UNSIGNED auto_increment NOT NULL,
        firstname CHARACTER VARYING(128) NOT NULL,
		lastname CHARACTER VARYING(128) NOT NULL,
		emailId CHARACTER VARYING(128) NOT NULL,
		age INTEGER NOT NULL, 
		gender VARCHAR(23) NOT NULL,
        teamid INTEGER UNSIGNED NOT NULL,
		FOREIGN KEY (teamid) REFERENCES Teams(teamid),
		PRIMARY KEY (playerid)
) ENGINE=INNODB auto_increment = 1000;